management:
  tracing:
    enabled: false
  #otlp:
    #tracing:
      #endpoint: http://localhost:4318/v1/traces
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint} traceId=%X{traceId:-} spanId=%X{spanId:-} %n]"

